1,什么是 Dockerfile？
Dockerfile 是一个用来构建镜像的文本文件，文本内容包含了一条条构建镜像所需的指令和说明。
2,使用 Dockerfile 定制镜像
2.1 创建一个dockerfile文件夹用于存入自己的镜像架包
mkdir  dockerfile

2.2 在dockerfile下也创建一个springboot文件夹
mkdir  springboot

2.3 把你的架包(我的架包是springbootdome.jar)上传到springboot文件夹中
rz

2.4 在springboot文件夹下创建一个Dockerfile
vi Dockerfile
内容如下：
FROM hub.c.163.com/library/java:8-alpine

VOLUME /tmp

RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

ADD springbootdome.jar app.jar

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

2.5 参数说明：
FROM 镜像地址，我这里获取的是网易镜像库的jdk8-alpine java版本，可自行去选择对应的版本
VOLUME 数据库挂载出来，用于容器接收数据指定宿主机接收地址，默认就是/tmp
RUN 运行对应的脚本，我这里是同步了宿主机和docker容器的时间
ADD 可以理解为将Dockerfile所在当前文件夹中springbootdome.jar 重命名
ENTRYPOINT 运行对应的jar包，-Djava.security.egd=file:/dev/./urandom大致意思是加快tomcat运行速度，可自行百度。

2.6 构建镜像
docker build -t springbootdome:0.1 springboot